### ISSUE TITLE
Unable to load LTTNG trace with floating point fields

### ISSUE THREAD

**Issue by KyleStorck** [microsoft/Microsoft-Performance-Tools-Linux#11]
I have recorded a couple basic trace events in WSL using LTTNG, and when I try to load that trace directory in WPA GUI, I get an error about one of my floating point event fields. When I remove all the floating point fields and use integers instead, it works and the trace loads. Is there support for floating fields? 

I am using binaries I got internally (). I was having trouble using binaries I got from this github.

![image](https://user-images.githubusercontent.com/1233941/107825677-6a109580-6d38-11eb-95b2-46e3996b093a.png)

Then a separate issue. When I did get the trace to load using integers, I didn't see the fields loaded in WPA. Is this something that should be working?

![image](https://user-images.githubusercontent.com/1233941/107826021-fb800780-6d38-11eb-803c-76622de5744c.png)

Thanks!

**Comment by ivberg** [comment]
We will start looking into this @KyleStorck. Can you send a repro trace?

**Comment by ivberg** [comment]
Partial working support here - https://github.com/microsoft/Microsoft-Performance-Tools-Linux/tree/user/ivberg/Fix11_LTTngFloatingPointTraceLoadIssue

**Comment by ivberg** [comment]
> Then a separate issue. When I did get the trace to load using integers, I didn't see the fields loaded in WPA. Is this something that should be working?

Yes that is desired be working but it looks unrelated to this float issue (as you said repro's on int). Not sure if this ever worked but I did try a few WPA versions and some older traces that seemed to have the same behavior not showing the fields values. LTTngDriver cmd-line accessed/displayed the fields fine so this is likely a separate UI issue we will need to work on.
